/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResortsIndexRouteImport } from './routes/resorts.index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResortsIdRouteImport } from './routes/resorts.$id'
import { Route as ManagerSupportRouteImport } from './routes/manager.support'
import { Route as ManagerResortsRouteImport } from './routes/manager.resorts'
import { Route as ManagerBookingsRouteImport } from './routes/manager.bookings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminResortsRouteImport } from './routes/admin.resorts'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResortsIndexRoute = ResortsIndexRouteImport.update({
  id: '/resorts/',
  path: '/resorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResortsIdRoute = ResortsIdRouteImport.update({
  id: '/resorts/$id',
  path: '/resorts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSupportRoute = ManagerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerResortsRoute = ManagerResortsRouteImport.update({
  id: '/resorts',
  path: '/resorts',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerBookingsRoute = ManagerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ManagerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResortsRoute = AdminResortsRouteImport.update({
  id: '/resorts',
  path: '/resorts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register': typeof RegisterRoute
  '/weather': typeof WeatherRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/resorts': typeof AdminResortsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/resorts': typeof ManagerResortsRoute
  '/manager/support': typeof ManagerSupportRoute
  '/resorts/$id': typeof ResortsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/resorts/': typeof ResortsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/weather': typeof WeatherRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/resorts': typeof AdminResortsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/resorts': typeof ManagerResortsRoute
  '/manager/support': typeof ManagerSupportRoute
  '/resorts/$id': typeof ResortsIdRoute
  '/admin': typeof AdminIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/resorts': typeof ResortsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/register': typeof RegisterRoute
  '/weather': typeof WeatherRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/resorts': typeof AdminResortsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/resorts': typeof ManagerResortsRoute
  '/manager/support': typeof ManagerSupportRoute
  '/resorts/$id': typeof ResortsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/resorts/': typeof ResortsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/manager'
    | '/register'
    | '/weather'
    | '/admin/bookings'
    | '/admin/resorts'
    | '/admin/tickets'
    | '/admin/users'
    | '/manager/bookings'
    | '/manager/resorts'
    | '/manager/support'
    | '/resorts/$id'
    | '/admin/'
    | '/manager/'
    | '/resorts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/weather'
    | '/admin/bookings'
    | '/admin/resorts'
    | '/admin/tickets'
    | '/admin/users'
    | '/manager/bookings'
    | '/manager/resorts'
    | '/manager/support'
    | '/resorts/$id'
    | '/admin'
    | '/manager'
    | '/resorts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/manager'
    | '/register'
    | '/weather'
    | '/admin/bookings'
    | '/admin/resorts'
    | '/admin/tickets'
    | '/admin/users'
    | '/manager/bookings'
    | '/manager/resorts'
    | '/manager/support'
    | '/resorts/$id'
    | '/admin/'
    | '/manager/'
    | '/resorts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  WeatherRoute: typeof WeatherRoute
  ResortsIdRoute: typeof ResortsIdRoute
  ResortsIndexRoute: typeof ResortsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resorts/': {
      id: '/resorts/'
      path: '/resorts'
      fullPath: '/resorts/'
      preLoaderRoute: typeof ResortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resorts/$id': {
      id: '/resorts/$id'
      path: '/resorts/$id'
      fullPath: '/resorts/$id'
      preLoaderRoute: typeof ResortsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/support': {
      id: '/manager/support'
      path: '/support'
      fullPath: '/manager/support'
      preLoaderRoute: typeof ManagerSupportRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/resorts': {
      id: '/manager/resorts'
      path: '/resorts'
      fullPath: '/manager/resorts'
      preLoaderRoute: typeof ManagerResortsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/bookings': {
      id: '/manager/bookings'
      path: '/bookings'
      fullPath: '/manager/bookings'
      preLoaderRoute: typeof ManagerBookingsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resorts': {
      id: '/admin/resorts'
      path: '/resorts'
      fullPath: '/admin/resorts'
      preLoaderRoute: typeof AdminResortsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminResortsRoute: typeof AdminResortsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminResortsRoute: AdminResortsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ManagerRouteChildren {
  ManagerBookingsRoute: typeof ManagerBookingsRoute
  ManagerResortsRoute: typeof ManagerResortsRoute
  ManagerSupportRoute: typeof ManagerSupportRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerBookingsRoute: ManagerBookingsRoute,
  ManagerResortsRoute: ManagerResortsRoute,
  ManagerSupportRoute: ManagerSupportRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  WeatherRoute: WeatherRoute,
  ResortsIdRoute: ResortsIdRoute,
  ResortsIndexRoute: ResortsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
